import getGroq from '../../lib/groq';

export interface GeneratedBlog {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
}

export interface BlogPreview {
  title: string;
  slug: string;
  excerpt: string;
  category: string;
  tags: string[];
  read_time_minutes: number;
}

export async function generateBlogList(category: string, count: number = 6): Promise<BlogPreview[]> {
  const prompt = `Generate a list of ${count} blog post previews for the category: "${category}".

Return ONLY a valid JSON object with a single key "blogs" containing an array of ${count} items.
Each item must have:
- title: engaging, SEO-friendly blog title
- slug: URL-friendly slug (lowercase, hyphens only, unique)
- excerpt: 2-3 sentence compelling summary
- category: "${category}"
- tags: array of 3-4 relevant tag strings
- read_time_minutes: estimated read time as a number

JSON only, no extra text.`;

  const response = await getGroq().chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [{ role: 'user', content: prompt }],
    response_format: { type: 'json_object' },
    temperature: 0.8,
  });

  const raw = response.choices[0].message.content ?? '{}';
  const parsed = JSON.parse(raw) as { blogs: BlogPreview[] };

  if (!Array.isArray(parsed.blogs) || parsed.blogs.length === 0) {
    throw new Error('No blogs generated by AI');
  }

  return parsed.blogs;
}

export async function generateBlogByTopic(topic: string): Promise<GeneratedBlog> {
  const prompt = `Generate a complete, high-quality blog post about: "${topic}".

Return ONLY a valid JSON object with these fields:
- title: An engaging, SEO-friendly blog title
- slug: A URL-friendly slug (lowercase, hyphens only)
- excerpt: A compelling 2-3 sentence summary
- content: Full blog post in markdown format (minimum 600 words), including an intro, 3-4 sections with headers, and a conclusion

JSON only, no extra text.`;

  const response = await getGroq().chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [{ role: 'user', content: prompt }],
    response_format: { type: 'json_object' },
    temperature: 0.7,
  });

  const raw = response.choices[0].message.content ?? '{}';
  const parsed = JSON.parse(raw) as GeneratedBlog;

  if (!parsed.title || !parsed.slug || !parsed.content || !parsed.excerpt) {
    throw new Error('Incomplete blog generated by AI');
  }

  return parsed;
}
